"use strict";

let chart = [
    {
        id: 1,
        firstname: "Miley",
        lastname: "Cyrus",
        age: 29,
        etnicity: "American",
        gender: "female",

    },
    {
        id: 2,
        firstname: "Kid",
        lastname: "Cudi",
        age: 38,
        etnicity: "American",
        gender: "male",
    },
    {
        id: 3,
        firstname: "Justin",
        lastname: "Bieber",
        age: 27,
        etnicity: "Canadian",
        gender: "male",
    },
    {
        id: 4,
        firstname: "Zara",
        lastname: "Larsson",
        age: 24,
        etnicity: "Swedish",
        gender: "female",
    },
    {
        id: 5,
        firstname: "Niall",
        lastname: "Horan",
        age: 28,
        etnicity: "Irish",
        gender: "male",
    },
    {
        id: 6,
        firstname: "Veronica",
        lastname: "Maggio",
        age: 40,
        etnicity: "Swedish",
        gender: "female",
    },
    {
        id: 7,
        firstname: "Snoop",
        lastname: "Dogg",
        age: 50,
        etnicity: "American",
        gender: "male",
    },
    {
        id: 8,
        firstname: "Selena",
        lastname: "Gomez",
        age: 29,
        etnicity: "American",
        gender: "female",
    },
    {
        id: 9,
        firstname: "Dua",
        lastname: "Lipa",
        age: 26,
        etnicity: "British",
        gender: "female",
    },
    {
        id: 10,
        firstname: "Justin",
        lastname: "Timberlake",
        age: 41,
        etnicity: "American",
        gender: "male",
    }
];