let database = [
    {
        id: 1,
        firstName: "Miley",
        lastName: "Cyrus",
        age: 29,
        etnicity: "American",
        gender: "female",

    },
    {
        id: 2,
        firstName: "Kid",
        lastName: "Cudi",
        age: 38,
        etnicity: "American",
        gender: "male",
    },
    {
        id: 3,
        firstName: "Justin",
        lastName: "Bieber",
        age: 27,
        etnicity: "Canadian",
        gender: "male",
    },
    {
        id: 4,
        firstName: "Zara",
        lastName: "Larsson",
        age: 24,
        etnicity: "Swedish",
        gender: "female",
    },
    {
        id: 5,
        firstName: "Niall",
        lastName: "Horan",
        age: 28,
        etnicity: "Irish",
        gender: "male",
    },
    {
        id: 6,
        firstName: "Veronica",
        lastName: "Maggio",
        age: 40,
        etnicity: "Swedish",
        gender: "female",
    },
    {
        id: 7,
        firstName: "Snoop",
        lastName: "Dogg",
        age: 50,
        etnicity: "American",
        gender: "male",
    },
    {
        id: 8,
        firstName: "Selena",
        lastName: "Gomez",
        age: 29,
        etnicity: "American",
        gender: "female",
    },
    {
        id: 9,
        firstName: "Dua",
        lastName: "Lipa",
        age: 26,
        etnicity: "British",
        gender: "female",
    },
    {
        id: 10,
        firstName: "Justin",
        lastName: "Timberlake",
        age: 41,
        etnicity: "American",
        gender: "male",
    }
];